#!/bin/sh

VERSION=$(git describe --tags | awk "{split(\$0,a,\"-\"); print a[1];}")

echo -e "package util\n\nconst Version = \"$VERSION\"" > internal/util/version.go

git add internal/util/version.go
git commit -m "change version number to $VERSION"

touch test.txt

exit 0