#!/bin/sh

VERSION=$(git describe --tags | awk "{split(\$0,a,\"-\"); print a[1];}")

echo -e "package util\n\nconst Version = \"$VERSION\"" > internal/util/version.go

git tag -d "$VERSION"
git tag -a "$VERSION" -m "$VERSION"