// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.

package firefly

import (
	domain "github.com/stnokott/firefly-import-helper/internal/domain"
	generated "github.com/stnokott/firefly-import-helper/internal/firefly/generated"
)

func ConvertAccount(source generated.AccountRead) domain.FireflyAccount {
	var domainFireflyAccount domain.FireflyAccount
	domainFireflyAccount.ID = source.Id
	domainFireflyAccount.Name = source.Attributes.Name
	domainFireflyAccount.Active = boolOrTrue(source.Attributes.Active)
	return domainFireflyAccount
}

func ConvertAccounts(source []generated.AccountRead) []domain.FireflyAccount {
	var domainFireflyAccountList []domain.FireflyAccount
	if source != nil {
		domainFireflyAccountList = make([]domain.FireflyAccount, len(source))
		for i := 0; i < len(source); i++ {
			domainFireflyAccountList[i] = ConvertAccount(source[i])
		}
	}
	return domainFireflyAccountList
}

func ConvertTransaction(source domain.BankTransaction, context string) *generated.TransactionSplitStore {
	generatedTransactionSplitStore := defaultTransactionSplitStore()
	pGeneratedTransactionSplitStore := &generatedTransactionSplitStore
	(*pGeneratedTransactionSplitStore).Amount = generated.Amount(source.Amount)
	(*pGeneratedTransactionSplitStore).BookDate = nullableFromTime(source.Date)
	(*pGeneratedTransactionSplitStore).CurrencyCode = nullableFromString(source.Currency)
	(*pGeneratedTransactionSplitStore).Date = copyTime(source.Date)
	(*pGeneratedTransactionSplitStore).Description = source.Description
	(*pGeneratedTransactionSplitStore).DestinationId = getDestinationID(source, context)
	(*pGeneratedTransactionSplitStore).DestinationName = getDestinationName(source)
	(*pGeneratedTransactionSplitStore).ExternalId = nullableFromString(source.ID)
	(*pGeneratedTransactionSplitStore).SourceId = getSourceID(source, context)
	(*pGeneratedTransactionSplitStore).SourceName = getSourceName(source)
	(*pGeneratedTransactionSplitStore).Type = mapDomainTransactionType(source.Type)
	return pGeneratedTransactionSplitStore
}

func ConvertTransactionSplit(source generated.TransactionSplit) *domain.TransactionRead {
	var domainTransactionCreated domain.TransactionRead
	domainTransactionCreated.Type = mapGeneratedTransactionType(source.Type)
	domainTransactionCreated.AccountName = getAccountName(source)
	domainTransactionCreated.MerchantName = getMerchantName(source)
	domainTransactionCreated.Amount = float64(source.Amount)
	domainTransactionCreated.CurrencySymbol = currencySymbolOrDefault(source.CurrencySymbol)
	domainTransactionCreated.Date = copyTime(source.Date)
	domainTransactionCreated.Description = source.Description
	domainTransactionCreated.Category = stringOrEmpty(source.CategoryName)
	return &domainTransactionCreated
}
