// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.

package firefly

import (
	domain "github.com/stnokott/firefly-import-helper/internal/domain"
	generated "github.com/stnokott/firefly-import-helper/internal/firefly/generated"
)

func ConvertAccount(source generated.AccountRead) domain.FireflyAccount {
	var domainFireflyAccount domain.FireflyAccount
	domainFireflyAccount.ID = source.Id
	domainFireflyAccount.Name = source.Attributes.Name
	domainFireflyAccount.Active = boolOrTrue(source.Attributes.Active)
	return domainFireflyAccount
}
func ConvertAccounts(source []generated.AccountRead) []domain.FireflyAccount {
	var domainFireflyAccountList []domain.FireflyAccount
	if source != nil {
		domainFireflyAccountList = make([]domain.FireflyAccount, len(source))
		for i := 0; i < len(source); i++ {
			domainFireflyAccountList[i] = ConvertAccount(source[i])
		}
	}
	return domainFireflyAccountList
}
