version: "2"

run:
  timeout: "3m"
linters:
  default: none
  enable:
    - errcheck
    - gocritic
    - govet
    - revive
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - decorder
    - goconst
    - nilerr
    - gocyclo
    - importas

  settings:
    revive:
      rules:
        - name: exported
          disabled: true
    errcheck:
      check-blank: false
    govet:
      enable-all: true
      disable:
        - fieldalignment
    goconst:
      match-constant: true
      min-len: 3
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - appendAssign

  exclusions:
    rules:
      - path: '(.+)_test\.go'
        linters: [goconst]
      - text: 'declaration of "(err|ctx)" shadows declaration at'
        linters: [govet]
