assert_lefthook_installed: true

pre-commit:
  parallel: true
  jobs:
    - run: go test -v ./...
      glob:
        - "*.go"
        - go.mod
        - go.sum
      tags: [test]
    - run: go mod tidy -diff
      glob:
        - "*.go"
        - go.mod
        - go.sum
      tags: [test]
    - run: golangci-lint run --config=.golangci.yaml
      glob:
        - "*.go"
        - go.mod
        - go.sum
      tags: [lint]
