repos:
  - hooks:
      - args:
          - mod
          - tidy
        entry: go
        fail_fast: true
        files: .mod
        id: go-mod-tidy
        language: golang
        name: go-mod-tidy
        pass_filenames: false
      - args:
          - test
          - -race
          - ./...
        entry: go
        fail_fast: true
        id: go-test-race
        language: golang
        name: go-test-race
        pass_filenames: false
    repo: local
  - hooks:
      - id: golangci-lint
    repo: https://github.com/golangci/golangci-lint
    rev: v1.47.2
  - hooks:
      - id: commitizen
    repo: https://github.com/commitizen-tools/commitizen
    rev: v2.38.0
