// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package server

import (
	client "github.com/stnokott/firefly-import-helper/internal/client"
	domain "github.com/stnokott/firefly-import-helper/internal/domain"
)

func ConvertWebhookResponse(source *WebhookResponse) *domain.Transaction {
	var pDomainTransaction *domain.Transaction
	if source != nil {
		var domainTransaction domain.Transaction
		domainTransaction.ID = (*source).Content.ID
		domainTransaction.CreatedAt = ConvertTime((*source).Content.CreatedAt)
		domainTransaction.User = (*source).Content.User
		if (*source).Content.SubTransactions != nil {
			domainTransaction.SubTransactions = make([]*domain.SubTransaction, len((*source).Content.SubTransactions))
			for i := 0; i < len((*source).Content.SubTransactions); i++ {
				domainTransaction.SubTransactions[i] = pServerWebhookResponseSubTransactionToPDomainSubTransaction((*source).Content.SubTransactions[i])
			}
		}
		pDomainTransaction = &domainTransaction
	}
	return pDomainTransaction
}
func pServerWebhookResponseSubTransactionToPDomainSubTransaction(source *WebhookResponseSubTransaction) *domain.SubTransaction {
	var pDomainSubTransaction *domain.SubTransaction
	if source != nil {
		var domainSubTransaction domain.SubTransaction
		domainSubTransaction.Amount = client.Amount((*source).Amount)
		domainSubTransaction.CurrencySymbol = (*source).CurrencySymbol
		if (*source).CategoryID != nil {
			xstring := *(*source).CategoryID
			domainSubTransaction.CategoryID = &xstring
		}
		if (*source).CategoryName != nil {
			xstring2 := *(*source).CategoryName
			domainSubTransaction.CategoryName = &xstring2
		}
		domainSubTransaction.Date = ConvertTime((*source).Date)
		domainSubTransaction.Description = (*source).Description
		domainSubTransaction.DestinationName = (*source).DestinationName
		domainSubTransaction.SourceName = (*source).SourceName
		if (*source).TransactionJournalID != nil {
			xstring3 := *(*source).TransactionJournalID
			domainSubTransaction.TransactionJournalID = &xstring3
		}
		domainSubTransaction.Type = ConvertTransactionType((*source).Type)
		domainSubTransaction.User = (*source).User
		pDomainSubTransaction = &domainSubTransaction
	}
	return pDomainSubTransaction
}
