// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.

package lunchflow

import (
	domain "github.com/stnokott/firefly-import-helper/internal/domain"
	"math"
)

func ConvertAccount(source Account) domain.BankAccount {
	var domainBankAccount domain.BankAccount
	domainBankAccount.ID = source.ID
	domainBankAccount.Name = source.Name
	domainBankAccount.Institution = source.InstitutionName
	domainBankAccount.Currency = currencyOrDefault(source.Currency)
	domainBankAccount.Status = ConvertAccountStatus(source.Status)
	return domainBankAccount
}
func ConvertAccountStatus(source AccountStatus) domain.BankAccountStatus {
	var domainBankAccountStatus domain.BankAccountStatus
	switch source {
	case AccountStatusActive:
		domainBankAccountStatus = domain.BankAccountStatusActive
	case AccountStatusDisconnected:
		domainBankAccountStatus = domain.BankAccountStatusDisconnected
	case AccountStatusError:
		domainBankAccountStatus = domain.BankAccountStatusError
	default:
		domainBankAccountStatus = domain.BankAccountStatusError
	}
	return domainBankAccountStatus
}
func ConvertAccounts(source []Account) []domain.BankAccount {
	var domainBankAccountList []domain.BankAccount
	if source != nil {
		domainBankAccountList = make([]domain.BankAccount, len(source))
		for i := 0; i < len(source); i++ {
			domainBankAccountList[i] = ConvertAccount(source[i])
		}
	}
	return domainBankAccountList
}
func ConvertTransaction(source Transaction) domain.BankTransaction {
	var domainBankTransaction domain.BankTransaction
	domainBankTransaction.ID = source.ID
	domainBankTransaction.IsPending = boolOrFalse(source.IsPending)
	domainBankTransaction.Type = determineTransactionType(source)
	domainBankTransaction.AccountID = source.AccountID
	domainBankTransaction.Amount = math.Abs(source.Amount)
	domainBankTransaction.Currency = source.Currency
	domainBankTransaction.Date = copyDateTime(source.Date)
	domainBankTransaction.Description = descriptionOrEmpty(source.Description)
	if source.Merchant != nil {
		xstring := *source.Merchant
		domainBankTransaction.Merchant = &xstring
	}
	return domainBankTransaction
}
func ConvertTransactions(source []Transaction) []domain.BankTransaction {
	var domainBankTransactionList []domain.BankTransaction
	if source != nil {
		domainBankTransactionList = make([]domain.BankTransaction, len(source))
		for i := 0; i < len(source); i++ {
			domainBankTransactionList[i] = ConvertTransaction(source[i])
		}
	}
	return domainBankTransactionList
}
